console.log(Boolean(6))
console.log(Boolean(-1))
console.log(Boolean(0.0))
console.log(Boolean(0))
console.log(Boolean("Mayank"))
console.log(Boolean("false"))
console.log(Boolean(-.1))
console.log(Boolean(""))
console.log(Boolean(" "))
console.log(Boolean("false"))